using System;
namespace BathroomBreak.Configuration
{
    public static class BathroomBreakConstants
    {
        // 2500 is a good value
        public static int SplashScreenTimeout { get { return 25; } }
        public static string TermsAndConditions { get; } = @"Consumer Terms of Use for BathroomBreak App & Web Sites

The network of web sites(collectively, the ""Web Sites"", ""Sites"",  ""Site"", or “App”) operated by Bathroom Break or its affiliates, subsidiaries, assigns, successors, brands, licensors, licensees, and/or agents is comprised of various web sites and web pages.The terms, conditions, and notices contained herein (collectively, ""Terms"") apply to all.In addition, Bathroom Break in particular Bathroom Break Mobile App or features and activities offered on such Sites(such as promotions and chat rooms) may also be subject to additional terms outlined on such Sites(""Additional Terms""), all of which are incorporated herein by reference.If any of the Terms contained herein conflict with the Additional Terms presented on any particular Bathroom Break applications, then the Additional Terms shall control.
Terms presented on any particular Bathroom Break application, then the Additional Terms shall control.
PLEASE READ THE FOLLOWING TERMS CAREFULLY BEFORE USING THIS APPLICATION OR OTHER BATHROOM BREAK APPLICATIONS.The Bathroom Break Applications are offered to you (the ""User"") conditioned on your acceptance without modification of the Terms and the applicable Privacy Statement.By accessing or using this Site or any other Site, you agree to these Terms and the applicable Privacy Statement. If you do not agree to these Terms, do not use this Site or any other Site.
PLEASE NOTE THAT THESE TERMS MAY REQUIRE YOU TO SUBMIT DISPUTES TO ARBITRATION AND REQUIRE THAT DISPUTES BE RESOLVED ONLY IN A FORUM IN HAMILTON COUNTY, OHIO.Please review the Applicable Laws and Disputes section of these Terms for complete details.


Privacy
Use of the Bathroom Break Applications is also subject to the Bathroom Break Consumer Privacy Statement(""Privacy Statement""). If a Site has additional, separate privacy provisions (""Additional Privacy Provisions""), then use of that Site is subject to those Additional Privacy Provisions. 
We use cookies and other technologies to collect information when you visit our sites including your IP address, web pages you view and links you click. We also use digital cookies in the emails that we send you to let us know you’ve received them. You can delete and decline cookies in your web browser. We may use this information, together with the information you provide us during the registration process on the application or otherwise, to send you information that may be of interest to you in accordance with our Privacy Statement. 
Personal Use of Sites
Unless otherwise specified, the Application is for your personal and noncommercial use only. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any of the content or communications featured or displayed on the Site (""Content""), including without limitation text, graphics, photographs, images, moving images, sound, illustrations, information, software, products or services and the arrangements thereof, except as expressly permitted hereunder. You acknowledge that any unauthorized use of any Content could cause irreparable harm to us and agree that in the event of any such unauthorized use, we will be entitled to an injunction in addition to any other remedies available at law or in equity. Subject to any expressly stated restrictions or limitations on the Site relating to specific material, you may electronically copy and/or print hard copy portions of Content solely for your own noncommercial use, or to place an order with us. Any other use of Content, including the modification, reproduction, distribution, republication, display or transmission of any Content, without our prior written permission, is strictly prohibited.
You agree not to collect and/or use any product descriptions, images, listings or prices except for your own personal noncommercial use or to place an order with us.
You agree that you will not reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any portion of the Application or use or access to the Application, including without limitation any ""scraping"" or using any robot, spider or other automated means.Running or displaying this Application or any information or material displayed on this Application in frames, via ""in-line"" linking or through similar means on another Web site without our prior written permission is prohibited.Any permitted links to this Web site must comply with all applicable laws, rule, and regulations. You may not use any meta tags or other ""hidden text"" utilizing our name or any of our trademarks, or those of any manufacturer of products featured on this Application, without express written permission. Additionally, you agree that you will not: (a) take any action that, in our sole discretion, imposes, or may impose an unreasonable or disproportionately large load on our infrastructure; (b) interfere or attempt to interfere with the proper working of the Application or any activities conducted on the Site; or (c) bypass any measures we may use to prevent or restrict access to the Site.

User Submissions
These Terms govern your conduct, your rights, and Bathroom Break’s rights with respect to any text, photograph, video, post, communication, music, audio/sound recording, artwork, ratings, reviews or other materials or information you make associated with the Bathroom Break Application (""Submission""). When you submit a Submission, you agree to the following:
●	your Submission is original, accurate, created by you, and not an impersonation;
●	you are currently a bona fide user of the Bathroom Break product(s) mentioned in your Submission and your Submission reflects your true and honest opinion of and current experience with the Bathroom Break products(s);
●	you are over the age of majority, or, if a minor, your parent or legal guardian consents to your submission;
●	you are not an employee of Bathroom Break nor do you work for an affiliate or agency of Bathroom Break hired by Bathroom Break to promote and/or sell Bathroom Break products; OR, if you are employee of Bathroom Break or work for an affiliate or agency of Bathroom Break hired by Bathroom Break to promote and/or sell Bathroom Break products, you agree to include a clear and conspicuous disclosure of your relationship with Bathroom Break in your Submission;
●	your Submission (or any portion of it) has not been included in nor planned for use in any other advertising or promotional materials, for Bathroom Break or any third party;
●	your Submission is made without any prior payment or promise of payment having been made to you or the expectation by you of any payment in return for your proposed Submission. Your Submission is also made without any prior benefit having been made to you or the expectation of any future benefit, except for the possibility of having your Submission used for  Bathroom Break promotional purposes. Or, if you did receive a benefit, you clearly disclose the details of the benefit in your Submission;
●	your Submission is not false, misleading, offensive, profane, vulgar, obscene, derogatory, defamatory, libelous, slanderous, or otherwise inappropriate;
●	your Submission does not contain content which infringes any third party's copyright, patent, trademark, trade secret, right of publicity, right of privacy, moral rights, and/or any other applicable personal or proprietary rights;
●	your Submission does not contain content which violates any law, statute, ordinance or regulation or content that engages in, encourages, advocates, or provides instructions for conduct that would constitute a criminal or civil offense under any law, statute, ordinance or regulation;
●	your Submission does not contain material or content that is, or may reasonably be considered to be, hate speech, whether directed at an individual or group, or that is otherwise unlawfully threatening or unlawfully harassing to any individual, partnership, corporation, or political body;
●	your Submission does not contain content or materials intended to create disruption or to mislead others, such as posting multiple Submissions in an effort to monopolize the forum or posting a Submission unrelated to the forum’s designated topic or theme;
●	your Submission does not contain content which includes third party websites, addresses, email addresses, contact information, phone numbers, other information or opinions about an identified or reasonably identifiable individual or private information(including sensitive information) without obtaining prior consent from that individual for sharing such information with Bathroom Break;
●	your Submission does not contain programming or materials containing any Trojan horses, viruses, worms, harmful code, or other potentially damaging information, programs, or file; and
●	Bathroom Break’s use of your Submission does not violate these Terms and will not cause injury to any person or entity.
If the Submission is related in any way to a promotion, sweepstakes, contest, giveaway, or similar program, Additional Terms may apply. Any opinions, advice, statements, services, offers, or other information contained in Submissions expressed or made available on the Application are those of the respective author(s) or distributor(s) and not of Bathroom Break. We neither endorse nor guarantee the accuracy, completeness, or usefulness of any such Submission.
Bathroom Break does not and cannot review all Submissions posted to or created by users accessing the Application and is not in any manner responsible for the content of these Submissions.You acknowledge that by providing you with the ability to view and distribute user-generated content on the Application, Bathroom Break is merely acting as a passive conduit for such distribution and is not undertaking any obligation or liability relating to any Submissions or activities on the Application.Bathroom Break will have no obligation to post or use any Submission(s). Bathroom Break reserves the right to block or remove Submissions and/or Users that it determines to be (a) abusive, defamatory, or obscene, (b) fraudulent, deceptive, or misleading, (c) in violation of a copyright, trademark or; other intellectual property rights of another or(d) violates any law or regulation or(e) offensive or otherwise unacceptable to Bathroom Break at its sole discretion.Note that any personally identifiable information you may post or transmit will be treated by Bathroom Break in accordance with Bathroom Breaks Privacy Statement.Except for any personally identifiable information we may collect from you under the guidelines established in our Privacy Statement, any Submission will be considered non-confidential and non-proprietary.Bathroom Break will have no obligations with respect to the Submissions.
By submitting a Submission, you grant each of the following to Bathroom Break:
●	a non-exclusive, worldwide, perpetual, irrevocable, fully paid-up, royalty-free, fully sublicensable and transferable right and license to use, monitor, review, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, transmit, display, and perform such Submission(s), in whole or in part, in any media, format or technology, online or offline, whether now known or hereafter discovered, and in any manner including, but not limited to, all promotional, public viewing and/or commenting(whether on Bathroom Break's applications or on third party web pages), advertising, marketing, merchandising, publicity, and commercial uses and ancillary uses thereof, without any further notice or payment to or permission needed from you (except where prohibited by law);
●	an unrestricted, worldwide, perpetual, irrevocable, fully paid-up, royalty-free, fully sublicensable and transferable right and license to use your name, nickname, user name, biographical information, vocal recordings of you, and/or any illustrations, photographic or video graphics clips, portraits, likenesses or pictures of you or any other indicia of your right of publicity rights (collectively ""Your Personal Content"") as contained in your Submission(s), in composite or distorted form or as otherwise incorporated into other creative works of authorship, in any media, format or technology, online or offline, whether now known or hereafter discovered, and in any manner including, but not limited to, all promotional, public viewing and/or commenting(whether on Bathroom Break's applications or on third party web pages), advertising, marketing, merchandising, publicity, and commercial uses and ancillary uses thereof, without any further notice or payment to or permission needed from you (except where prohibited by law).
You also agree to waive any applicable moral rights as contained in your Submission(s) for any of the proposed uses listed above.
By submitting a Submission, you agree to release, hold harmless and indemnify on behalf of yourself and your successors, assigns and representatives and Bathroom Break each of its respective officers, directors, and employees from and against any and all claims, suits, actions, demands, liabilities and damages of any kind whatsoever arising out of or in connection with the use of such Submission, including, without limitation, any and all claims for false advertising, copyright infringement, invasion of privacy, violation of the right of publicity or of moral rights, and/or defamation. Without limiting the foregoing, in no event will you be entitled to, and you waive any right to, enjoin, restrain or interfere with the use of the Submission or Your Personal Content embodied in such Submission or the exploitation of any of the Bathroom Break's rights as noted above.
You understand that Bathroom Break is relying upon your representations, grants of rights, waivers, and releases in permitting you to submit a Submission. You acknowledge that you may not terminate or rescind the grants of rights and licenses and/or the releases contained in this Agreement.
Bathroom Break does not guarantee that you will have an opportunity to edit or delete your Submission.You acknowledge that you, not Bathroom Break, are responsible for the contents of any Submission(s).

Code of Conduct
By accessing or using any Application or any other feature provided through our Application, including but not limited to, when submitting a Submission to our Application, you agree to abide by the following standards of conduct.You agree that you will not, and will not authorize or facilitate any attempt by another person or entity to:
●	Use the Application in breach of these Terms;
●	Reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any portion of any Application or use or access to the Application;
●	Harass, threaten, stalk or intentionally embarrass or cause distress to another person or entity;
●	Impersonate another person or entity;
●	Promote, solicit, or participate in any multilevel marketing or pyramid schemes;
●	Solicit personally identifiable information from or exploit any individual under eighteen(18) years of age;
●	Engage in disruptive activity such as sending multiple messages in an effort to monopolize the forum or posting unrelated to a forum’s designated topic or theme;
●	Introduce viruses, worms, Trojan horses, harmful code, or any software or other materials that contain a component harmful to the application;
●	Gain unauthorized access to any computer system or nonpublic portion of the Application or interfere with or disrupt the Application, servers, or networks connected to the Application;
●	Invade the privacy of any person, including posting personally identifying or otherwise private or sensitive information about a person without their consent or harvesting personally identifiable information about the Applications’ users;
●	Engage in, encourage, advocate, provide instructions for or discuss with the intent to commit conduct that would constitute a criminal or civil offense or otherwise violate any federal, state, local, or international law or regulation.
Bathroom Break cannot and does not assure that other Users are or will be compliant with the foregoing Code of Conduct or any other provisions of these Terms, and, as between you and us, you hereby assume all risk of harm or injury resulting from any such lack of compliance.

Contact Us
If these Terms do not address your question, or if you would like to report a violation of our Code of Conduct, please contact us as follows:
E-mail
Please email us at bathroombreak19@gmail.com
Copyright 2001—2020 Bathroom Break.All rights reserved.";
    }
}
